#!/bin/bash

awk ' \

{
 l=length($0)
 if (l>130) {
  id=substr($0, 49, 6)
  seq=substr($0,62,60)
  nres=substr($0, 124, 4)
  name=substr($0, 130, l)
  
  print id" "seq" "nres" "name
 } else
  { 
#   print "%"
  }
} ' align.txt
 
 