#!/bin/bash


for i in `echo 0 1 2 3 4 5` ; do

f=emr-tpp-dmpcn-eq${i}.res ;
echo Procesing $f ...
awk '
BEGIN {FIELDWIDTHS=" 6 5 1 4 1 3 1 1 4 1 3 8 8 8 6 6 6 4" ; RT=""} 

{ 
 if ($1 == "ATOM  ") {
  segid=$18 ;
  if ( ( segid == "EMR1" ) || ( segid == "EMR2" ) || ( segid == "TPP " ) ) {
   $15="0.00" ;
  } else if ( ( segid == "MEMB" ) || ( segid == "TIP3" ) || ( segid == "ION1" ) || ( segid == "ION2" ) ) {
   $15="3.00" ;
  }

  printf "%6s",$1
  printf "%5d", $2
  printf "%1s", $3
  printf "%4s", $4
  printf "%1s", $5
  printf "%3s", $6
  printf "%1s", $7
  printf "%1s", $8
  printf "%4s", $9
  printf "%4s", $10
  printf "%8s", $12
  printf "%8s", $13
  printf "%8s", $14
  printf "%6s", $15
  printf "%6s", $16
  printf "%6s", $17
  printf "%4s\n", $18
 }

} ' < $f > _temp ;
mv _temp $f

done


f=emr-tpp-dmpcn-protein.res ;
echo Procesing $f ...
awk '
BEGIN {FIELDWIDTHS=" 6 5 1 4 1 3 1 1 4 1 3 8 8 8 6 6 6 4" ; RT=""} 

{ 
 if ($1 == "ATOM  ") {
  segid=$18 ;
  if ( ( segid == "EMR1" ) || ( segid == "EMR2" ) || ( segid == "TPP " ) ) {
   $15="0.00" ;
  } else if ( ( segid == "MEMB" ) || ( segid == "TIP3" ) || ( segid == "ION1" ) || ( segid == "ION2" ) ) {
   $15="3.00" ;
  }

  printf "%6s",$1
  printf "%5d", $2
  printf "%1s", $3
  printf "%4s", $4
  printf "%1s", $5
  printf "%3s", $6
  printf "%1s", $7
  printf "%1s", $8
  printf "%4s", $9
  printf "%4s", $10
  printf "%8s", $12
  printf "%8s", $13
  printf "%8s", $14
  printf "%6s", $15
  printf "%6s", $16
  printf "%6s", $17
  printf "%4s\n", $18
 }

} ' < $f > _temp ;
mv _temp $f

f=emr-tpp-dmpcn-tpp.res ;
echo Procesing $f ...
awk '
BEGIN {FIELDWIDTHS=" 6 5 1 4 1 3 1 1 4 1 3 8 8 8 6 6 6 4" ; RT=""} 

{ 
 if ($1 == "ATOM  ") {
  segid=$18 ;
  if ( ( segid == "EMR1" ) || ( segid == "EMR2" ) || ( segid == "TPP " ) ) {
   $15="0.00" ;
  } else if ( ( segid == "MEMB" ) || ( segid == "TIP3" ) || ( segid == "ION1" ) || ( segid == "ION2" ) ) {
   $15="3.00" ;
  }

  printf "%6s",$1
  printf "%5d", $2
  printf "%1s", $3
  printf "%4s", $4
  printf "%1s", $5
  printf "%3s", $6
  printf "%1s", $7
  printf "%1s", $8
  printf "%4s", $9
  printf "%4s", $10
  printf "%8s", $12
  printf "%8s", $13
  printf "%8s", $14
  printf "%6s", $15
  printf "%6s", $16
  printf "%6s", $17
  printf "%4s\n", $18
 }

} ' < $f > _temp ;
mv _temp $f

