#!/bin/bash

if [ -z "$1" ]; then
 echo 'USAGE: convert1 <filename>';
 exit 1
else
 file="$1"
 name=${file%.*}
# echo $name
 echo -n "converting "$file" to "$name.$2" ..."
# convert -density 200 -antialias -quality 100 $file $name.$2
 convert -density 100 -quality 100 "$file" "$name.$2"
 echo 'done'
fi
 