#!/bin/bash
# download consistent packages from archlinux archive
pkgs=(
python-cffi-1.16.0-2  python-cryptography-42.0.6-1  python-pycparser-2.22-2
)

baseurl="https://archive.archlinux.org/packages"
ext1="x86_64.pkg.tar.zst"
ext2="any.pkg.tar.zst"

for pkg in ${pkgs[@]} ; do
 first_letter=${pkg:0:1}
# pkgname=${pkg%%-[0-9]*}
#echo $pkgname
#continue
 url=$baseurl/$first_letter/${pkgname}/${pkg}-${ext1}
 echo "Fetching $pkg @ $url"
 response=`wget $url 2>&1`
 notfound=`echo $response | grep 'ERROR 404'`
 if [[ ! -z $notfound ]] ; then
  url=$baseurl/$first_letter/${pkgname}/${pkg}-${ext2}
  echo "Fetching $pkg @ $url"
  response=`wget $url 2>&1`
  notfound=`echo $response | grep 'ERROR 404'`
  if [[ ! -z $notfound ]] ; then
   echo "Could not find $pkg"  
  fi
 fi
 pacman -Udd ${url##*/}
done
