#!/bin/bash
# combine multiple parameters file into one for acemd
#

outpar=mergepar.par
echo -n > $outpar

echo "* combined CHARMM parameter file; generated automatically for ${outpar}" > _header
echo "!" >> _header
echo -n > _bond
echo -n > _angl
echo -n > _dihe
echo -n > _impr
echo -n > _cmap
echo -n > _nbnd
echo -n > _nbfx

for arg in "$@" ; do
 echo "processing file "$arg"..."

awk 'BEGIN \
{
     readbond=0 ; readangl=0 ; readdihe=0 ; readcmap=0 ; readnbnd=0 ; readnbfx=0 ; readimpr=0 ; outfile="/dev/null";
     prmfile=ARGV[1];
}
{
  if        ( substr($1,0,5) ~ /[Bb][Oo][Nn][Dd][Ss]/) { 
     readbond=1 ; readangl=0 ; readdihe=0 ; readcmap=0 ; readnbnd=0 ; readnbfx=0 ; readimpr=0  ; outfile="_bond";
  } else if ( substr($1,0,6) ~ /[Aa][Nn][Gg][Ll][Ee][Ss]/) { 
     readbond=0 ; readangl=1 ; readdihe=0 ; readcmap=0 ; readnbnd=0 ; readnbfx=0 ; readimpr=0  ; outfile="_angl";
  } else if ( substr($1,0,4) ~ /[Dd][Ii][Hh][Ee]/) { 
     readbond=0 ; readangl=0 ; readdihe=1 ; readcmap=0 ; readnbnd=0 ; readnbfx=0 ; readimpr=0  ; outfile="_dihe";
  } else if ( substr($1,0,4) ~ /[Ii][Mm][Pp][Rr]/) { 
     readbond=0 ; readangl=0 ; readdihe=0 ; readcmap=0 ; readnbnd=0 ; readnbfx=0 ; readimpr=1  ; outfile="_impr";
  } else if ( substr($1,0,4) ~ /[Cc][Mm][Aa][Pp]/) { 
     readbond=0 ; readangl=0 ; readdihe=0 ; readcmap=1 ; readnbnd=0 ; readnbfx=0 ; readimpr=0  ; outfile="_cmap";
  } else if ( substr($1,0,4) ~ /[Nn][Oo][Nn][Bb]/) { 
     readbond=0 ; readangl=0 ; readdihe=0 ; readcmap=0 ; readnbnd=1 ; readnbfx=0 ; readimpr=0  ; outfile="_nbnd";
  } else if ( substr($1,0,4) ~ /[Nn][Bb][Ff][Ii]/) { 
     readbond=0 ; readangl=0 ; readdihe=0 ; readcmap=0 ; readnbnd=1 ; readnbfx=1 ; readimpr=0  ; outfile="_nbfx";
  } else if ( ( substr($1,0,3) ~ /[Ee][Nn][Dd]/) || (substr($1,0,2) ~ /[Ii][Cc]/) || (substr($1,0,5) ~ /[Dd][Oo][Nn][Oo]/) \
     || (substr($1,0,4) ~ /[Aa][Cc][Cc][Ee]/) ) { 
     readbond=0 ; readangl=0 ; readdihe=0 ; readcmap=0 ; readnbnd=0 ; readnbfx=1 ; readimpr=0  ; outfile="/dev/null";
  }
    else if ((substr($1,0,1)!="!") && (substr($1,0,5) !~ /[Cc][Uu][Tt][Nn][Bb]/) && (substr($1,0,5) !~ /[Hh][Bb][Oo][Nn][Dd]/)) {
     print $0 >> outfile
  }
 }
 ' $arg

done
#
# ad hoc : remove nbfix entry
#SOD    OCL      -0.075020   3.190 ! For lipid carboxylate groups
sed -i 's/.*For lipid carboxylate groups//' _nbfx

# now concatenate
cat _header     >$outpar
echo BONDS     >>$outpar
cat _bond      >>$outpar
echo ANGLES    >>$outpar
cat _angl      >>$outpar
echo DIHEDRALS >>$outpar
cat _dihe      >>$outpar
echo IMPROPERS >>$outpar
cat _impr      >>$outpar
echo CMAP      >>$outpar
cat _cmap      >>$outpar
echo NONBONDED >>$outpar
cat _nbnd      >>$outpar
echo NBFIX     >>$outpar
cat _nbfx      >>$outpar
echo END       >>$outpar

rm -f _header _bond _angl _dihe _impr _cmap _nbfx _nbnd
