#!/bin/bash
# Victor Ovchinnikov 2014
# Combine multiple parameters file into one for namd/acemd
# Any parameter conflicts or duplications are not taken into account
#

outpar=acemd.prm
echo -n > $outpar

echo "* combined parameter file for NAMD/ACEMD simulations; generated automatically for by mergepar" > _header
echo "!" >> _header
echo -n > _bond
echo -n > _angl
echo -n > _dihe
echo -n > _impr
echo -n > _cmap
echo -n > _nbnd
echo -n > _nbfx

for arg in "$@" ; do
 echo "processing file "$arg"..."

awk 'BEGIN \
{
     outfile="/dev/null";
     prmfile=ARGV[1];
}
{
  if        ( substr($1,0,5) ~ /[Bb][Oo][Nn][Dd][Ss]/) { 
     outfile="_bond";
  } else if ( substr($1,0,6) ~ /[Aa][Nn][Gg][Ll][Ee][Ss]/) { 
     outfile="_angl";
  } else if ( substr($1,0,8) ~ /[Dd][Ii][Hh][Ee][Dd][Rr][Aa][Ll]/) { 
     outfile="_dihe";
  } else if ( substr($1,0,8) ~ /[Ii][Mm][Pp][Rr][Oo][Pp][Ee][Rr]/) { 
     outfile="_impr";
  } else if ( substr($1,0,4) ~ /[Cc][Mm][Aa][Pp]/) { 
     outfile="_cmap";
  } else if ( substr($1,0,4) ~ /[Nn][Oo][Nn][Bb]/) { 
     outfile="_nbnd";
  } else if ( substr($1,0,4) ~ /[Nn][Bb][Ff][Ii]/) { 
     outfile="_nbfx";
  } else if ( substr($1,0,3) ~ /[Ee][Nn][Dd]/) { 
     outfile="/dev/null";
  }
    else if ((substr($1,0,1)!="!") && (substr($1,0,5) !~ /[Cc][Uu][Tt][Nn][Bb]/) && (substr($1,0,5) !~ /[Hh][Bb][Oo][Nn][Dd]/)) {
     print $0 >> outfile
  }
 }
 ' $arg

done
#
# ad hoc : remove nbfix entry
#SOD    OCL      -0.075020   3.190 ! For lipid carboxylate groups
sed -i 's/.*For lipid carboxylate groups//' _nbfx

# now concatenate
cat _header     >$outpar
echo BONDS     >>$outpar
cat _bond      >>$outpar
echo ANGLES    >>$outpar
cat _angl      >>$outpar
echo DIHEDRALS >>$outpar
cat _dihe      >>$outpar
echo IMPROPERS >>$outpar
cat _impr      >>$outpar
echo CMAP      >>$outpar
cat _cmap      >>$outpar
echo NONBONDED >>$outpar
cat _nbnd      >>$outpar
echo NBFIX     >>$outpar
cat _nbfx      >>$outpar
echo END       >>$outpar

rm -f _header _bond _angl _dihe _impr _cmap _nbfx _nbnd
echo $outpar
