#!/bin/bash
#
function exists() { # returns 1 if command $1 exists, 0 otherwise
  cmd=$1
  if command -v $cmd >/dev/null 2>&1; then
   echo 1
  else
   echo 0
  fi
}
if [ `exists psfgen` -eq 0 ]; then
 echo "ERROR : This script requires PSFGEN from the NAMD distribution"
 exit 1
fi

psffile=./dhfr_sn
pdbfile=./dhfr_msn

newname="${psffile}hh" ;

psfgen << END
readpsf ${psffile}.psf pdb ${pdbfile}.pdb
#hmassrepart dowater 1 mass 4 ;# 1st argument specifies whether to repartition water ; second, sets the H mass (default is 3.024) ; NAMD3 crashes w/4
hmassrepart dowater 1 mass 3.024
writepsf ${newname}.psf ; # the geniuses decided to write charmm-incompatible psf files; so have to try to clean up below
#writepdb ${newname}.pdb
END

sed -i 's/^\ *REMARK(\?S)*/*/' ${newname}.psf # to change remarks to stars
sed -i '/NCRTERM/i \       0       0 !NUMLP NUMLPH\n' ${newname}.psf # insert number of lone pairs (0) ; NOTE : \n is essential for correctness
# note that the above is still insufficient because psfgen does not read group definitions from the original PDB ; CHARMM uses them in basically _all_ versions
# of the nonbonded routines.
# Below, set the number of groups to zero, which make charmm run using BYCU, or BYCC (set in chmene):
sed -i 's/.*NGRP/\       0       0 !NGRP/' ${newname}.psf
# The better fix would be to actually recreate the group lists, e.g. by copying from the original psf :

#~/scripts/chmene ${newname}.psf ${newname}.pdb `ls ../../*top` `ls ../../*par`
~/scripts/chmene ${psffile}hh.psf ${pdbfile}.pdb `ls ../../*top` `ls ../../*par`
