#!/bin/bash
# align trajectory with the HA in Harrison's structure
#
# write out chain B from Harrison's pdb, which will be used for alignment
#
~/scripts/getchain 6e4x.pdb B | grep ATOM > chainB.pdb
#
# loop over traj and align every frame to chainB

echo -n \
'#!/bin/tcl
#set psffile trunc1/2viu-trunc-dry ;#trunc
set psffile full/2viu-dry ;# full
mol load pdb ${psffile}.pdb
set step 1
mol addfile ${psffile}.dcd waitfor all step $step
set hiv [molinfo top]
set ha12 [atomselect $hiv "segname HA11"] ;# HA12 for trunc2, H11 for others
set all [atomselect $hiv "all"]

set nf [molinfo $hiv get numframes]
for {set i 0} {$i<$nf} {incr i} {
 put $i
 $ha12 frame $i
 $ha12 writepdb frame.pdb
 set out [exec TMalign frame.pdb chainB.pdb -m mat.txt]
 set out [exec awk "{if ( \$1 ~ \/\[1-3\]\/) print \$2\" \"\$3\" \"\$4\" \"\$5}" mat.txt];
# puts $out
#parse out for rotation matrix
 set m {};
 foreach {m1 m2 m3 m4} $out {
  lappend m " $m2 $m3 $m4 $m1 "
 }
 lappend m { 0. 0. 0. 1.}
# puts $m
# rotate dcd frame
 $all frame $i
 $all move $m
# $ha12 writepdb frame-rot.pdb
# return
}
# write trajectory
animate write dcd ${psffile}-aln.dcd waitfor all
'>tmp.vmd
vmd -dispdev text < tmp.vmd
rm tmp.vmd mat.txt
