#!/bin/bash

# awk program for modifying PDB files
# arg(1) file to process
# arg(2) file with commands

 while read line ; do
 cmd=`echo $line | awk ' { print tolower(substr($1,1,3))}'`
# echo $cmd
 if [  "$cmd" == "hse" ]; then
  HISE=${line##HSE}
 continue
 fi
 if [  "$cmd" == "hsd" ]; then
  HISD=${line##HSD}
 continue
 fi
 if [  "$cmd" == "hsp" ]; then
  HISP=${line##HSP}
 continue
 fi
 if [  "$cmd" == "gln" ]; then
  GLNE=${line##GLN}
 continue
 fi
 if [  "$cmd" == "asn" ]; then
  ASNE=${line##ASN}
 continue
 fi
 if [  "$cmd" == "hsw" ]; then
  HISFLIP=${line##HSW}
 continue
 fi
 done <$2

awk  -v HISE="$HISE" -v HISD="$HISD" -v HISP="$HISP" -v GLNE="$GLNE" -v ASNE="$ASNE" -v HISFLIP="$HISFLIP" '
      BEGIN { 

      $0=HISE
      for (i=1; i<=NF; i++) {
       HSE[$i]=1
      }
      $0=HISD
      for (i=1; i<=NF; i++) {
       HSD[$i]=1
      }
      $0=HISP
      for (i=1; i<=NF; i++) {
       HSP[$i]=1
      }
      $0=HISFLIP
      for (i=1; i<=NF; i++) {
       HISflip[$i]=1
      }
      $0=ASNE
      for (i=1; i<=NF; i++) {
       ASN[$i]=1
      }
      $0=GLNE
      for (i=1; i<=NF; i++) {
       GLN[$i]=1
      }
      FIELDWIDTHS="6 5 1 4 1 3 1 1 4 1 3 8 8 8 6 6 6 4"
    }

 {
    if ($1 == "ATOM  " ) {
      resid=$9 + 0 ;#convert string to number
      if ( resid in HSD ) {
       if ( $4 ~ "\\s*CA\\s*" ) print "Changing "$6" "resid" to HSD" >"modpdb.log"
       sub($6, "HSD");
#       print $0
      } else if ( resid in HSE ) {
       if ( $4 ~ "\\s*CA\\s*" ) print "Changing "$6" "resid" to HSE" >"modpdb.log"
       sub($6, "HSE");
#       print $0
      } else if ( resid in HSP ) {
       aname=$4
       if ( $4 ~ "\\s*CA\\s*" ) print "Changing "$6" "resid" to HSP" >"modpdb.log"
       sub($6, "HSP");
#       print $0
      } else if ( resid in HISflip ) {
        print $6" flip:" resid >"modpdb.log"
       if ( $4 ~ "\\s*ND1\\s*") {
        sub ($4, " CD2");
       } else if ($4 ~ "\\s*CD2\\s*") {
       sub ($4, " ND1");
       } else if ($4 ~ "\\s*CE1\\s*") {
       sub ($4, " NE2");
       } else if ($4 ~ "\\s*NE2\\s*") {
       sub ($4, " CE1");
       }
      } else if ( resid in GLN ) {
       if ( $4 ~ "\\s*OE1\\s*") {
        sub ($4, " NE2");
        print $6" flip:" resid >"modpdb.log"
       } else if ($4 ~ "\\s*NE2\\s*") {
       sub ($4, " OE1");
       }
      } else if ( resid in ASN ) {
       if ( $4 ~ "\\s*OD1\\s*") {
        sub ($4, " ND2");
        print $6" flip:" resid >"modpdb.log"
       } else if ($4 ~ "\\s*ND2\\s*") {
       sub ($4, " OD1");
       }
    }
   }
 print $0
} ' $1 

