#!/bin/bash 
# remove code protected by STRINGM, MULTICOM, NEWBESTFIT
source=oldsource ; # existing source directory

dirs=`ls $source`;

newsource=newsource ; # new source directory
tempfile=temp.src ;

# one at a time :
#dirs=charmm
#dirs=dynamc
#dirs=machdep
#dirs=io
#dirs=energy
#dirs=util
#dirs=mscale

for d in $dirs ; do
 echo Processing directory \"${d}\"
 mkdir -p ${newsource}/${d}
 files=`ls ${source}/${d}` ;
 for f in $files ; do
  oldfile=$source/$d/$f
  newfile=$newsource/$d/$f
# skip directories
  if [ ! -d $oldfile ] ; then
   ./rmkey STRINGM $oldfile > $tempfile
   ./rmkey MULTICOM $tempfile > $newfile
   ./rmkey NEWBESTFIT $newfile > $tempfile
   mv $tempfile $newfile
# check how the files differ
   diff $oldfile $newfile > __diff
   if [ ! -s __diff ] ; then # diff file has zero size, so simply copy over the old file (to keep the mod date)
    cp $oldfile $newfile
   fi
  else # simply copy this directory
   echo $f is a directory
   cp -rf $oldfile $newfile
  fi
#  exit
 done
 diff -r $source/$d $newsource/$d > ${d}.diff
done