#!/bin/bash
# extract text from text file
# hacked to remove "\hide{ ... } " from latex files
if [ -z "$2" ] ; then 
 echo " USAGE : xtext <filename> <start_pattern> <end_pattern>"
 exit 1;
else
 file="$1"
 from="$2"
fi

# allow offsets to beginning and ending lines
if [ -z $4 ]; then
 boff=0
else
 boff=$4
fi

if [ -z $5 ]; then
 eoff=0
else
 eoff=$5
fi

lbeg=`grep -En --text "${from}" $file|awk '{print $0}'`
#
if [[ -z $lbeg  ]] ; then
 exit
fi
#
lbeg=`expr ${lbeg%%:*} + $boff`

if [ -z "$3" ]; then
 lend=`wc $file | awk '{print $1}'`
else
 to="$3"
 lends=`grep -En --text "${to}" $file|awk '{print $0}' | sed 's/:\}//g'`
#echo $lends
 for lend in $lends ; do
  if [ $lend -gt $lbeg ] ; then
   break
  fi
 done
 lend=`expr ${lend%%:*} + $eoff`
fi
lquit=`expr $lend + 1`
echo $lbeg
echo $lend
scmd="${lbeg},${lend}p;${lquit}q"
#echo $scmd
#echo $ssymb
#sed -n "$scmd" $file
