#!/bin/bash
# write x y z coordinates followed by charge in four columns
# using a pdb and a psf file
#
if [ -z $2 ] ; then 
 echo "USAGE : xyzq <pdbfile> <psffile>"
 exit 1;
else
 pdbfile=$1
 psffile=$2
fi

awk '
 BEGIN {FIELDWIDTHS="6 5 1 4 1 3 1 1 4 1 3 8 8 8 6 6 6 4"
    }
{
 if ( (substr($1,0,4) == "ATOM") || (substr($1,0,6) == "HETATM" ) ) {
  print $12" "$13" "$14
 }
} ' $1 > _xyz

awk '
{ 
 if ( $0 ~ /^\s*[0-9]+\s*!\s*[Nn][Aa][Tt][Oo][Mm]*/ ) {
  qatom=1;
 } else if ( $0 ~ /^\s*[0-9]+\s*!\s*[Nn][Bb][Oo][Nn][Dd]*/ ) {
  exit
 } else if ( NF>=7 && qatom ) {
  { print $7 };
 }
} ' $2 > _q

paste _xyz _q
rm -f _xyz _q

