% compute & plot energies computed with openMM ; OBC2 GB model for nonbond interactions
% based on mksasa
qoct=exist('OCTAVE_VERSION');
if (qoct) ; graphics_toolkit('gnuplot'); end
%
fpath='dcd';
fnames={
'h7-fi6-noc15'
'h7-fi6-noc15-fab1'
'h7-fi6-noc15-fab2'
'h7-fi6-noc15-fab3'
'h7-fi6-noc15-notfab1'
'h7-fi6-noc15-notfab2'
'h7-fi6-noc15-notfab3'
}

qblock=0; % obtain errors from block averaging or correlation analysis (qblock=0)
% NOTE : qblock=1 gives somewhat higher errors, but both methods seem consistent

%read all data, assuming it fits into the same array (can mod later for generality)
% actually, read the last xxK values (the first 1 or 2 are the minimized pdb coords)
i=1;
numval=8000; % note that this can be set smaller to empirically account for a transient
clear ene;
ibond=1 ; iangle=2 ; idihe=3 ; iub=4 ; iimpr=5 ; icmap=6 ; inb=7 ; ipe=8 ; % note that there is no separate term for OBC2
% ^ Note that the GB energy calculation does not separate NB energies into vdw, electrostatic, solvation ; I think it is straightforward in Openmm, requiring
%   reassignment to different force groups
iene=inb ; % which energy term to compare
%
for fname=fnames(:)'
% NOTE : each file name has a header generated by the trajectory loading script
 printf('Reading %s\n', fname{1})
 fid=fopen([fpath,'/',fname{1},'.ene'],'r');
 filestring=textscan(fid,'%s', 'delimiter', '\n');
 filestring=filestring{1};
 ind=strfind(filestring,'Bond'); % find line which has 'Bond' energy label
 ind2=find(1-cellfun(@isempty,ind));
 labels=textscan(filestring{ind2},'%s') ;
 labels=labels{1};
 numene=numel(labels);
 d=reshape( str2num( [ filestring{ind2+1:end} ]), numene, [])' ; % this contains the energy values from the output file
 ene(:,i)=d(end-numval+1:end,iene);
 i=i+1;
end

%plot ene series (they will be noisy and correlated, but we should get a gist of the trends/convergence)
plot(ene) ;% all at once ; looks converged, but a very crude vis ;
% use block averaging to compute average + sd
nene=numel(fnames);
aene=mean(ene,1); % sample means
%ene=bsxfun(@minus,ene,aene); % subtract mean
if (qblock) % for block averaging
for i=1:nene
% follow flyvbjerg and petersen 89, p. 463
 d=ene(:,i);
 j=1;
 bsize(j)=1;
 while 1
  nsamp(j)=numel(d);
%  c0 = sum(d.^2) / nsamp(j); %manual
  c0=var(d,1);
  vene(j,i)=c0/(nsamp(j)-1);
  verrene(j,i)=vene(j,i) / sqrt(2*(nsamp(j)-1));
  if (nsamp(j)<4) ; break ; end % next series will only have one sample, so stop
% otherwise, continue
  j=j+1;
  d = 0.5 * ( d(1:2:end-1) + d(2:2:end) );
  nsamp(j)=numel(d);
  bsize(j)=2*bsize(j-1);
 end
end
% plot estimates of stderr
% note: the error just keeps increasing -- i.e. does not converge ; however, we can still estimate the error
stdene=sqrt(vene);
plot(bsize,stdene,'o-') ; set(gca, 'xscale','log') ; xlabel('block size') ; ylabel('std err');
%errorbar(sqrt(vene),verrene,'o-')
%%%%%% index of the blocking data
blkind=10 % by eye
%
stdeene=stdene(blkind,:);
else % qblock
addpath('~/scripts/simonson-util/matlab/');
samps={};
for i=1:nene
 fprintf('Processing dataset %d\n',i);
% follow flyvbjerg and petersen 89, p. 463
 d=ene(:,i);
 cl=floor(acorr(d)); % correlation length
 samp=[];
 ibeg=1;
 iend=cl
 while iend<=numel(d)
  samp=[samp mean( d(ibeg:iend) ) ];
  ibeg=iend+1;
  iend=iend+cl;
 end
 samps{i}=samp;
 stdeene(i)=sqrt(var(samp)/numel(samp));
end
end
%return
% compute & plot ene :
inds = [1 2 5 ; 1 3 6 ; 1 4 7 ]; % which entries are combines
coefs= -1 * [-1 1 1 ;-1 1 1 ; -1 1 1 ];
for k=1:size(inds,1)
 ind=inds(k,:);
 coef=coefs(k,:);
 binde(k) = aene(ind)*coef';
 bindee(k)= sqrt ( stdeene(ind).^2 * abs(coef)' );
end

binde
bindee
data=[binde;bindee];
save('-ascii', ['h7-fi6-d',labels{iene},'.dat'],'data')
% compute average BSA :
