#!/bin/bash
# extract potential energy from CHOMM.py output

if [ -z "$1" ]; then
 echo "USAGE : ./gete <output file(s)>";
 exit 1;
fi

files=${@}

efile="e.dat"
echo -n > $efile

for f in $files ; do
# echo $f
#assume that the valid lines have time steps that are multiples of 10; convert to kcal / mol
 grep -e "^[1-9][0-9]*00\+ " $f | awk '{print $1" " $2 / 4.184" " $3 / 4.184" " $4" " $5}' >> $efile
done

t=1;
pe=2;
ke=3;
temp=4;
speed=5 ;

istart=5; # to skip initial entries

#echo "graphics_toolkit('gnuplot');\
#      e=load('$efile'); \
#      e=e($istart,$speed) ; \
#      fprintf('%12.5f',mean(e));\
#      fprintf('+/-%12.5f\n',std(e));\
#      hist(e,10) ;\
#      pause(100);" | octave
octave<<EOF
%graphics_toolkit('gnuplot');
e=load('$efile');
e=e($istart,$speed);
fprintf('%12.5f',mean(e));
fprintf('+/-%12.5f\n',std(e));
%hist(e,10);
%pause(100);
EOF
