#!/bin/bash
# extract potential energy from CHOMM.py output

if [ -z "$1" ]; then
 echo "USAGE : ./gete <output file(s)>";
 exit 1;
fi

files=${@}

efile="e.dat"

for f in $files ; do
# echo $f
#assume that the valid lines have time steps that are multiples of 10; convert to kcal / mol
 grep -e "^[1-9][0-9]*00\+ " $f | awk '{print $1" " $2 / 4.184" " $3 / 4.184" " $4 }' >> $efile
done

t=1;
pe=2;
ke=3;
temp=4;

echo "graphics_toolkit('gnuplot');\
      e=load('$efile'); \
      e=e(:,4) ; \
      fprintf('%12.5f',mean(e));\
      fprintf('+/-%12.5f\n',std(e));\
      hist(e,25) ;\
      pause(100);" | octave
