#!/bin/bash

#couldn't get awk to work; using sed
#awk '{ sub("/\cM/","", $0); print($0) }' $1 

sed 's/\cM//' $1 >temp_
#awk '{ if (substr($0,1,1) != "!") { print "     ",$0} else { print $0} }' temp_
mv -f temp_ $1
rm -f temp_

