#!/bin/bash
# render high resolution image from vmd using Tachyon 
# note: investigate use of
# -auto-skylight X [0-1]
# -rescale-lights X
# -add-skylight X
# -normalfixup guess for older scene files

tachyon=tachyon
tachyon=/usr/local/lib/vmd/tachyon_LINUXAMD64
# default Tachyon options
OPTS=" -aasamples 32 -mediumshade "

if [ -z $1 ] ; then 
 echo "USAGE: render <scene_file>"
 exit 1
fi

# set magnification -- default is 2, which quadruples the resolution
if [ -z $2 ] ; then
 scale=2
else
 scale=$2
fi  

if [ -f $1 ]; then
 res=`grep Resolution $1`;
 xres=`echo $res | awk '{print $2}'`;
 yres=`echo $res | awk '{print $3}'`;
 xres=`echo $xres*$scale|bc`;
 yres=`echo $yres*$scale|bc`;
 
 echo "Rendering scene file $1 to $1.tga at resolution $xres $yres."
 $tachyon $OPTS -res $xres $yres $1 -o ${1}_hi.tga
fi  
 

