#!/bin/bash

dir=${PWD##*/}

name=( struc/*sn.psf )
name=${name[0]%sn*}
name=${name##*/}
echo $name

skip=1;
p=100 ;
vmd -dispdev text -args $name $skip <rmsd.vmd
gnuplot << EOF
#set term dumb ;
plot "rmsd.dat" w lines ; pause 100
EOF
#echo "clear graphics_toolkit;graphics_toolkit('gnuplot');d=load(\"rmsd.dat\"); plot(d); pause($p);"|octave
#echo "d=load(\"rmsd.dat\"); plot(d); ylim([0 10.0]) ; pause($p);"|octave

exit
echo "\
clear graphics_toolkit;\
graphics_toolkit('gnuplot');\
d=load('rmsd.dat');\
 t=(1:length(d))*0.04 * $skip;\
 plot(t,d); \
 xlabel('t(ns)', 'fontsize',14); \
 ylabel('RMSD(Ang)', 'fontsize',14); \
 set(gca,'fontsize',14); \
 title('${dir}: RMSD from initial structure');\
 print(gcf,'-depsc2','${dir}-rmsd.eps');\
 "|octave
gv ${dir}-rmsd.eps

