#!/bin/bash
#
# driver program to launch equilibration and production of multiple structures
#
# all (or a subset of) directories :
dirs=`ls -d e{eh_,he}*`

for d in $dirs ; do
 echo "Processing directory $d ..."
#continue
 pushd $d >&/dev/null
 # check if this directory is done
 lastrun=eq9eq;
 if [ -f $lastrun ] ; then
  ok=`grep "dx.doi.org/doi:10.1021/ct9000685" $lastrun` ;# paper doi shown after successful runs
  if [ ! -z "$ok" ]; then
   popd >&/dev/null
   continue ;# skip this directory
  fi
 fi
 cp ../aceeq .
 sed -i "s/name=.*/name=$d/" aceeq
 nohup ./aceeq ../modyn eq >& eq.out
 popd >&/dev/null
# exit
done