#!/bin/bash

# on cyrus2
#charmrun=~/namd/NAMD_2.6_Linux-amd64-TCP/charmrun
#namd2=~/namd/NAMD_2.6_Linux-amd64-TCP/namd2

# on daedlalus1
#charmrun=~/namd/NAMD_2.6_Linux-amd64-TCP/charmrun
#namd2=~/namd/NAMD_2.6_Linux-amd64-TCP/namd2

jobid=0

name=m6rigtr
template=cpt

nsteps=100000
firststep=0

 output=cpt_
 flag=""
 for nrun in `seq 1 6`
 do
   count=$(($nrun-1))
   script=_$output$count$flag

   echo '#!/bin/vmd' > $script
   echo '#variable parameters (automatic)' >> $script
   grep -i set boxsize.str | awk '{ print tolower($0)}' >> $script

   echo set count $count >> $script 
   echo set cswitch on  >> $script
   echo set cscale `echo 30-$count*6 |bc `  >> $script
   
   echo set fixedflag off >>$script
   echo set consCol O >>$script

   echo set name $name >> $script
   echo set output $output$count$flag >>$script
   echo set restart $output$(($count-1))$flag >>$script

   if [ $count -eq 0 ] ; then 
    echo set shake off                       >> $script
    echo set dt .5                          >>$script
   else
    echo set shake all                       >> $script
    echo set dt 2.0                          >> $script
   fi
   echo set firstTstep     $firststep       >> $script
   echo set stepspercycle 10                >>$script
  
   echo set nsteps $nsteps                   >> $script
   cat $template >> $script
  
#use qsub:
######################

workdir=`pwd`

queue=debug
jname=$output
nodes=512

if [ $jobid != "0" ]; then

 jobid=`qsub <<_job1
#PBS -l mppwidth=$nodes,walltime=00:30:00
#PBS -N $jname$count
#PBS -o $jname.out
#PBS -e $jname.err
#PBS -q $queue
#PBS -V
#PBS -W depend=afterok:$jobid
cd $workdir
aprun -n $nodes namd2 $script >& $output$count$flag
_job1`
else
 jobid=`qsub <<_job0
#PBS -l mppwidth=$nodes,walltime=00:30:00
#PBS -N $jname$count
#PBS -o $jname.out
#PBS -e $jname.err
#PBS -q $queue
#PBS -V
cd $workdir
aprun -n $nodes namd2 $script >& $output$count$flag
_job0`
fi

 echo $jobid

######################
 if [ $? -ne 0 ];  then
   echo Execution interrupted due to errors during run $nrun.
   exit
 fi 
 
 firststep=$(($firststep+$nsteps))
 
 done

