#!/bin/tcl
#FEP parameters
#

alch		$alch
alchtype	FEP
alchfile	$alchpdb
alchcol		O
alchoutfile	${fepcount}-${alambda}-${alambda2}.fep
alchoutfreq	$alchfreq

alcheleclambdastart	1.0
alchvdwlambdaend	1.0
#alchvdwshiftcoeff	4.0
alchdecouple		on

alchequilsteps	$alcheqstep ;# note : I find this option essentially useless because one can just discard some data at the beginning

alchlambda	$alambda
alchlambda2	$alambda2
