#!/bin/bash
if test -z "$1"
then 
 echo "USAGE: namdtime output_file"
 exit 1
else
 log=$1
fi

# handle both cases
grep "Benchmark" $log | grep "days/ns" | awk '{print 1/$8}' > bench.tmp
#grep "TIMING" $log | grep "ns/day" | awk '{print $9}' >> bench.tmp
grep "Benchmark" $log | grep "ns/day" | awk '{print $8}' >> bench.tmp
echo "d=load('bench.tmp'); da=mean(d) ; de=std(d) ; fprintf([num2str(da),' +/- ',num2str(de),'\n'])" | octave
