#!/bin/bash

if [ -z $1 ]; then 
 echo "Error: filename(s) missing..."
 exit
fi

freq=10;

#psffile=../clpx_cg_ring.psf
dcds=$@

for dcdin in $dcds; do
#echo $dcdin
dcdout=${dcdin%%.*}_s.${dcdin#*.}
script=vmdscript

echo "#!/bin/tcl" > $script
echo >> $script
#echo mol load psf $psffile ;# dcd $dcdin waitforall >> $script
echo animate read dcd $dcdin beg 0 skip $freq waitfor all >> $script
echo animate write dcd $dcdout beg 0 skip 1 waitfor all sel [atomselect top all]>> $script
echo >> $script

vmd<$script
done
rm -f vmdscript
