#!/bin/bash

design=27


blib=~/scripts
clib=~/scripts/charmm
charmm=charmm327 # _repo

drug=apo

if [ 1 -eq 0 ]; then

mpirun -np 4 $charmm -i todo.inp -o todo.out # remove RANK & minimize the dry traf structure (again)
#fi
#exit
mpirun -np 4 $charmm psffile=traf-${drug} corfile=traf-${drug}-q2 buf=10.5 \
 cgenff=1 cube=1 topparcgenff=~/charmm/parameters/cgenff31 -i ${clib}/boxsolv.inp -o boxsolv.out

mpirun -np 4 $charmm psffile=traf-${drug}_s corfile=traf-${drug}-q2s istrength=0 \
  cgenff=1 topparcgenff=~/charmm/parameters/cgenff31 -i ${clib}/ionize.inp -o ionize.out
fi

# add silcs ligands
#mpirun -np 4 \
$charmm psffile=traf-${drug}_sn corfile=traf-${drug}-q2sn \
  cgenff=1 topparcgenff=~/charmm/parameters/cgenff31 -i ${clib}/silcs.inp -o silcs.out

# make acemd parameter file
${blib}/mergepar ~/charmm/parameters/c36/par_all36_prot_glup.prm \
                 ~/charmm/parameters/c36/toppar_water_ions.str \
                 ~/charmm/parameters/cgenff31/par_all36_cgenff.prm

# make topology file (needed to use codes other than acemd)
${blib}/mergetop ~/charmm/parameters/c36/top_all36_prot.rtf \
                 ~/charmm/parameters/c36/toppar_water_ions.str \
                 ~/charmm/parameters/cgenff31/top_all36_cgenff.rtf

mv mergepar.par traf-${drug}.par
mv mergetop.top traf-${drug}.top

# clean up :
#rm *-m.* *-ms.* *_s.psf *${drug}.pdb *${drug}.psf
