#!/bin/bash
qgnu=0;

datafile="tmp.dat"

what="Total force"
what="Total rigid-body"
what="Volume of bulk"
what="Mass of bulk"
#what="Instantaneous density"
#what="Simulation density"
#what="Surface energy"
#what="Curvature energy"
#what="Surface boundary distance"
#what="on a solvent atom"
#what="Surface boundary distance"
#what="Simulation density"
what="Surface curvature at solvent"

offset=$1
if [[ -z $offset ]]; then offset=1 ; fi;

grep -hi "$what" *in*log | awk -F '[:()]' "{print \$(NF-$offset)}" > $datafile
cat $datafile
#grep -hi "$what" *in*log | awk -F ':|\\(c' '{print $2}' > $datafile
#grep -hi "$what" *in*log | awk -F ':|\\(c' '{print $2}'
#exit
if [[ $qgnu -eq 1 ]]; then
gnuplot <<EOF
#set term dumb
plot '$datafile' with linespoints
pause 100
EOF
else
octave <<EOF
graphics_toolkit('gnuplot') ;
d=load("$datafile") ;
fprintf('%12.5f +/- %12.5f [%12.5f, %12.5f] \n', mean(d), std(d), min(d), max(d))
plot(d,'k.-')
pause
EOF
fi