#!/bin/bash
# renames water residues consecutively in a pdb;
# splits waterssegments with more than 99999 molecules into segments
# make sure the initial segment name has only two characters because an index will be appended

awk '\

BEGIN {
 infile  = ARGV[1];
 outfile = ARGV[2];
 ARGV[2]="";

 resnum=1;
 resid="";
 start=1; #flag
 segnum=1;
 blank="    ";
}

{
   if ($1 == "ATOM") {
       resid=substr($0,24,4); # extract resid
       segid=substr($0,73,4); # extract segment id
       match(segid, "[^ ]*",seg); #remove space & put patch into seg

       if ( start == 1) {start=0; resold = resid};
       if ( resid != resold ) {
                                resnum++;
				resold=resid;
                                if (resnum>=10000) {
				   resnum = 1; 
				   if (segnum == "") {segnum=1;}
				   else {segnum++;} # start over
				  } 
         }			    
	residnew=substr(blank,1,4-length(""resnum))""resnum ;  # pad with blanks
        str1=substr($0, 1, 27);
        sub(str1, substr($0,1,22)" "residnew); # substitute residue number
        str1=substr($0, 1, 76);
        sub(str1, substr($0,1,72)""seg[0]""segnum); # substitute residue number

        print $0>outfile""segnum".pdb"
    } 
 }
 ' $1 $2


