#!/bin/bash

dir=${PWD##*/}
echo $dir
skip=10;
p=100 ;
vmd -dispdev text <rmsd.vmd
#echo 'plot "rmsd.dat" w lines ; pause 10; '|gnuplot
#echo "clear graphics_toolkit;graphics_toolkit('gnuplot');d=load(\"rmsd.dat\"); plot(d); pause($p);"|octave
#echo "d=load(\"rmsd.dat\"); plot(d); ylim([0 10.0]) ; pause($p);"|octave
#exit 1
echo "\
clear graphics_toolkit;\
graphics_toolkit('gnuplot');\
d=load('rmsd.dat');\
 t=(1:length(d))*0.04;\
 plot(t,d); \
 xlabel('t(ns)', 'fontsize',14); \
 ylabel('RMSD(Ang)', 'fontsize',14); \
 set(gca,'fontsize',14); \
 title('${dir}: RMSD from initial structure');\
 print(gcf,'-depsc2','${dir}-rmsd.eps');\
 "|octave
gv rmsd.eps

