#!/bin/bash

#module load cuda
#module load cpe
#module load cpe-cuda

ROOT=$HOME/usr
export OPENMM_HOME=$ROOT
export DYNAMO_LIB_DIR=$ROOT/victor/lib
export OPENMM_LIB_DIR=$OPENMM_HOME/lib
export OPENMM_PLUGIN_DIR=$OPENMM_LIB_DIR/plugins
export LD_LIBRARY_PATH=$OPENMM_LIB_DIR:$OPENMM_PLUGIN_DIR:$DYNAMO_LIB_DIR:$LD_LIBRARY_PATH:

PYTHON=`which python`
pyver=`$PYTHON -V | awk '{print $2}'`
pyver=${pyver%.*}

# NOTE : PWD means this works in the current dir only
PYTHON_LOCAL=$PWD/openmm/build/python/build/lib.linux-x86_64-${pyver}:$ROOT/victor/plugin_master/openmm-dynamo/build/python/build/lib.linux-x86_64-${pyver}
export PYTHONPATH=$PYTHON_LOCAL:$PYTHON_LOCAL
#echo $PYTHON_LOCAL
#echo $LD_LIBRARY_PATH
export OMP_NUM_THREADS=32
export OMP_STACKSIZE=10M
export OMP_SCHEDULE=static
export OMP_NESTED=false

export CRAY_ACCEL_TARGET=nvidia86
export OPENMM_CUDA_COMPILER=`which nvcc`

#run benchmark
pushd dhfr
mkdir -p scratch
python ./md.py
popd
